version: "3.1"
services:
  mongo:
    image: mongo:6.0.4
    restart: always
    profiles:
      - dev
    env_file:
      - .env
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017
